#dataset: 'torchvision-cifar10'
num_classes: 1000
model: 'mae_vit_base_patch16_224'
log_wandb: False
wandb_experiment: 'CoAtNet-Cifar10'
pretrained: False

color_jitter: 0.0
hflip: 0.5
weight_decay: 0.05
opt: 'adamw'
sched: 'cosine'
lr: 0.0024 # base lr 1.5e-4  4096 * base / 256
epochs: 100
warmup_epochs: 5
cooldown_epochs: 0