dataset: 'torchvision-cifar100'
num_classes: 100

model: 'coatnet_0'
#input_size: 3 32 32

weight_decay: 0.1
clip_grad: 1.0

sched: 'step'
lr: 0.001
epochs: 164
warmup_epochs: 0
decay_epochs: 81 # 122