#dataset: 'torchvision-cifar10'
num_classes: 1000
model: 'coatnet_0_1k'

# Data Augmentation
aa: 'rand-m15-n2'
amp: True
hflip: 0.0
mixup: 0.8

#input_size: 3 32 32


weight_decay: 0.05
clip_grad: 1.0
opt: 'adamw'

sched: 'cosine'
lr: 0.0005 # 论文 bs4096 + lr 1e-3
min_lr: 0.000005
warmup_lr: 0.000005

epochs: 300
warmup_epochs: 5 # Imagenet1K bs4096 * 10K steps
cooldown_epochs: 0

use_dwconv: True