dataset: 'torchvision-cifar10'
num_classes: 10

model: 'swin_tiny_patch4_window7_224'
input_size: 3 224 224


weight_decay: 0.03
#clip_grad: 1.0
opt: 'adamw'

drop_path: 0.2
sched: 'cosine'
lr: 0.0005
epochs: 200
warmup_epochs: 0
